# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#2e2b28'
# soft contrast background = = '#32302f'
foreground = '#e6d8c8'

# Normal colors
[colors.normal]
black   = '#1a1919'
red     = '#cc241d'
green   = '#81981a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b8329b'
cyan    = '#ffab1f'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#333232'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#b36496'
cyan    = '#ffad1f'
white   = '#e6d8c8'
